import type { GlossaryTerm } from './types';

/**
 * Three glossaries in one searchable index: SQL, BigQuery and Marketing.
 *
 * Definitions are written for someone reading them mid-task, so each one leads with
 * what the thing *is* and follows with when it bites.
 */

const t = (
  term: string,
  category: GlossaryTerm['category'],
  short: string,
  long: string,
  extra: Partial<GlossaryTerm> = {},
): GlossaryTerm => ({ term, category, short, long, ...extra });

export const GLOSSARY: GlossaryTerm[] = [
  // ───────────────────────────────────────────────────────────── SQL ──
  t('Aggregate function', 'SQL',
    'A function that collapses many rows into one value.',
    'COUNT, SUM, AVG, MIN and MAX. Aggregates run after WHERE and before HAVING, which is why you can filter groups with HAVING but not with WHERE.',
    { related: ['GROUP BY', 'HAVING'] }),
  t('Alias', 'SQL',
    'A temporary name for a column or table, given with AS.',
    'Column aliases exist only in the output, so WHERE cannot see them — WHERE runs before SELECT. ORDER BY can, because it runs after.',
    { related: ['Logical query order'] }),
  t('Anti-join', 'SQL',
    'A pattern for finding rows with no match: LEFT JOIN then filter for NULL.',
    'Not a join type. `LEFT JOIN b ON … WHERE b.key IS NULL` keeps exactly the left rows that matched nothing. NOT EXISTS does the same job and is immune to the NOT IN + NULL trap.',
    { related: ['LEFT JOIN', 'NOT IN'] }),
  t('CTE', 'SQL',
    'Common Table Expression — a named intermediate result defined with WITH.',
    'A CTE does not make a query faster; in BigQuery it is not even materialised. It makes the query readable and lets you reference the same intermediate result more than once. That is reason enough.',
    { related: ['Subquery', 'Derived table'] }),
  t('Cardinality', 'SQL',
    'The number of distinct values in a column.',
    'High-cardinality columns (user ids) make poor GROUP BY keys for reporting and good cluster keys for filtering. Low-cardinality columns (status) are the reverse.',
    { related: ['Grain'] }),
  t('Correlated subquery', 'SQL',
    'A subquery that references a column from the outer query.',
    'It runs once per outer row, which is readable and slow. At small scale nobody notices; at millions of rows the LEFT JOIN + GROUP BY equivalent does the same work in one pass.',
    { related: ['Subquery', 'EXISTS'] }),
  t('Cross join', 'SQL',
    'Every row on the left paired with every row on the right.',
    'No ON clause — that is what makes it a cross join. Deliberate use: building a complete scaffold like a date spine. Accidental use: a missing join condition, and a query that never finishes.',
    { related: ['Date spine', 'Fan-out'] }),
  t('Date spine', 'SQL',
    'A complete list of dates that facts are LEFT JOINed onto.',
    'Without one, a day with no activity has no row at all, and a line chart draws straight through the gap. Missing and zero look identical on a graph and mean completely different things.',
    { related: ['Cross join', 'LEFT JOIN'] }),
  t('Derived table', 'SQL',
    'A subquery in the FROM clause — effectively an unnamed CTE.',
    'Functionally equivalent to a CTE. Prefer the CTE when the step deserves a name, which is most of the time.',
    { related: ['CTE', 'Subquery'] }),
  t('DISTINCT', 'SQL',
    'Removes duplicate rows across the entire select list.',
    '`SELECT DISTINCT a, b` gives distinct *pairs*, not distinct a and distinct b. It also only removes exact duplicates — near-duplicates need ROW_NUMBER.',
    { related: ['Deduplication'] }),
  t('Deduplication', 'SQL',
    'Removing repeated records for the same entity.',
    'DISTINCT works only for exact duplicates. The general solution is ROW_NUMBER() OVER (PARTITION BY key ORDER BY <which one to keep>) = 1, where the ORDER BY encodes the business rule.',
    { related: ['ROW_NUMBER', 'DISTINCT'] }),
  t('EXISTS', 'SQL',
    'Tests whether a subquery returns any row at all.',
    'The columns the subquery selects are irrelevant, which is why the convention is SELECT 1. NOT EXISTS is the safe alternative to NOT IN, because NULLs cannot break it.',
    { related: ['NOT IN', 'Anti-join'] }),
  t('Fan-out', 'SQL',
    'Row multiplication caused by joining to a finer grain.',
    'Join orders to order_items and each order appears once per line item. Summing an order-level column afterwards inflates it — in this warehouse by 2.19×. Nothing errors. Aggregate each side to a common grain before joining.',
    { related: ['Grain', 'Cross join'] }),
  t('Grain', 'SQL',
    'What one row of a table represents.',
    'One row per order, per campaign-day, per event. Almost every analytical bug is a grain mistake: summing at the wrong level, counting a duplicated dimension, or joining two facts without collapsing either first. State the grain before you write the query.',
    { related: ['Fan-out', 'Cardinality'] }),
  t('GROUP BY', 'SQL',
    'Collapses rows into one per distinct combination of the grouped columns.',
    'Every non-aggregated column in SELECT must appear in GROUP BY. You can group by an expression, and if you do, the same expression must appear in both places or the groups will not collapse.',
    { related: ['HAVING', 'Aggregate function'] }),
  t('HAVING', 'SQL',
    'Filters groups after aggregation.',
    'WHERE filters rows before grouping; HAVING filters groups after. `WHERE SUM(x) > 100` is an error because at WHERE time the sum does not exist yet.',
    { related: ['GROUP BY', 'Logical query order'] }),
  t('INNER JOIN', 'SQL',
    'Keeps only rows matching on both sides.',
    'The default and the one that silently deletes data. Every unmatched row on either side disappears without a warning, which is how orphaned foreign keys quietly vanish from reports.',
    { related: ['LEFT JOIN', 'Anti-join'] }),
  t('LEFT JOIN', 'SQL',
    'Keeps every row from the left table, NULL-filling the right.',
    'The critical rule: a condition on the *right* table belongs in ON, not WHERE. In WHERE it tests NULL for unmatched rows, fails, and silently converts your LEFT JOIN into an INNER JOIN.',
    { related: ['INNER JOIN', 'ON vs WHERE'] }),
  t('Logical query order', 'SQL',
    'The order clauses actually execute: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT.',
    'This single fact explains most beginner errors: why WHERE cannot see a SELECT alias, why HAVING can see aggregates, why ORDER BY can use aliases, and why LIMIT never reduces the work done.',
    { related: ['HAVING', 'Alias'] }),
  t('NOT IN', 'SQL',
    'Excludes values in a list — and returns nothing at all if the list contains a NULL.',
    '`x NOT IN (1, 2, NULL)` is never TRUE, it is UNKNOWN, because x might equal the unknown value. The query runs, returns zero rows, and looks like a finding. Use NOT EXISTS instead.',
    { related: ['EXISTS', 'NULL'] }),
  t('NULL', 'SQL',
    'The absence of a value — not zero, not empty string.',
    'NULL is not equal to anything, including itself. Only IS NULL / IS NOT NULL can see it. Any comparison with NULL yields UNKNOWN, and WHERE keeps only TRUE — which is why `!=` filters silently drop NULL rows.',
    { related: ['Three-valued logic', 'COALESCE'] }),
  t('COALESCE', 'SQL',
    'Returns the first non-NULL of its arguments.',
    'The tool for supplying a default. Ask whether the default is honest first: COALESCE(quality_score, 0) turns "unmeasured" into "terrible", which may not be what you want.',
    { related: ['NULL', 'IFNULL'] }),
  t('ON vs WHERE', 'SQL',
    'Where a join condition lives changes what an outer join returns.',
    'Conditions on the right-hand table of a LEFT JOIN go in ON. Conditions on the left-hand table go in WHERE. Getting this backwards is the highest-frequency JOIN bug there is, and it fails silently.',
    { related: ['LEFT JOIN'] }),
  t('Primary key', 'SQL',
    'The column (or columns) that uniquely identify a row.',
    'BigQuery does not enforce them. Never assume a column named *_id is unique — check with COUNT(*) vs COUNT(DISTINCT id). In this warehouse, orders.order_id is not.',
    { related: ['Foreign key', 'Grain'] }),
  t('Foreign key', 'SQL',
    'A column holding values that exist as keys in another table.',
    'Also unenforced in BigQuery. Orphaned references — pointing at rows that no longer exist — are normal, and an INNER JOIN deletes them from your report without saying so.',
    { related: ['Primary key', 'Anti-join'] }),
  t('QUALIFY', 'SQL',
    'Filters on a window function, the way HAVING filters on an aggregate.',
    'A BigQuery extension. Elsewhere you wrap the query in a subquery and filter outside it, because a window function is not available in WHERE.',
    { related: ['Window function', 'HAVING'] }),
  t('ROW_NUMBER', 'SQL',
    'Numbers rows 1, 2, 3 within each partition.',
    'Never ties — it picks arbitrarily unless you add a tie-break to the ORDER BY. That determinism is what makes it the right tool for deduplication and top-N-per-group.',
    { related: ['RANK', 'Window function'] }),
  t('RANK vs DENSE_RANK', 'SQL',
    'Both handle ties; they differ in what comes next.',
    'RANK ties then skips (1, 1, 3). DENSE_RANK ties then continues (1, 1, 2). Use either to report a placing, and ROW_NUMBER when you need to pick exactly one row.',
    { related: ['ROW_NUMBER'] }),
  t('Self join', 'SQL',
    'Joining a table to itself with two aliases.',
    'Needs an inequality in the ON clause or you get every pair twice plus every row paired with itself. Window functions have replaced most legitimate uses.',
    { related: ['Window function'] }),
  t('Subquery', 'SQL',
    'A query nested inside another.',
    'Scalar subqueries return one value and can sit anywhere a value can. Table subqueries sit in FROM. IN/EXISTS subqueries sit in WHERE. All three are useful; a CTE is usually more readable.',
    { related: ['CTE', 'Correlated subquery'] }),
  t('Three-valued logic', 'SQL',
    'SQL conditions evaluate to TRUE, FALSE or UNKNOWN.',
    'WHERE keeps only TRUE. Any comparison involving NULL is UNKNOWN, so both `x = 5` and `x != 5` exclude rows where x is NULL. If you want them, say `OR x IS NULL` explicitly.',
    { related: ['NULL', 'NOT IN'] }),
  t('Window function', 'SQL',
    'An aggregate that returns a value per row instead of collapsing rows.',
    'Two things nothing else can do: compare a row to its own group without a self-join, and look at neighbouring rows. Almost every "period over period", "top N per group" and "running total" request is one of those.',
    { related: ['Window frame', 'QUALIFY'] }),
  t('Window frame', 'SQL',
    'Which rows the window function actually sees.',
    'With ORDER BY and no explicit frame the default is UNBOUNDED PRECEDING to CURRENT ROW. That makes running totals work and makes LAST_VALUE return the current row — the classic surprise.',
    { related: ['Window function'] }),

  // ──────────────────────────────────────────────────────── BigQuery ──
  t('Bytes scanned', 'BigQuery',
    'What on-demand BigQuery actually bills for.',
    'Not rows returned, not query time. LIMIT does not reduce it. The three levers are: name fewer columns, prune partitions, and filter on cluster keys.',
    { related: ['Partitioning', 'Dry run'] }),
  t('Clustering', 'BigQuery',
    'Physically sorting rows within each partition by chosen columns.',
    'Used left to right like a composite index. Free to add and useless if you never filter or aggregate on the cluster key. Choose the columns from your actual WHERE clauses.',
    { related: ['Partitioning', 'Bytes scanned'] }),
  t('Dataset', 'BigQuery',
    'A container for tables, one level below the project.',
    'Fully qualified names are `project.dataset.table`. Datasets have a location, and you cannot join across regions.',
    { related: ['Project'] }),
  t('Dry run', 'BigQuery',
    'Estimating a query\'s bytes scanned without running it.',
    'The console validator shows it automatically; `bq query --dry_run` from the CLI. Pair it with `maximum_bytes_billed` so a runaway query fails instead of billing you.',
    { related: ['Bytes scanned'] }),
  t('Partitioning', 'BigQuery',
    'Physically splitting a table by a column, usually a date.',
    'A filter directly on the partitioning column lets BigQuery skip whole partitions. Wrap that column in any function and pruning stops working — transform the constant instead.',
    { related: ['Clustering', 'Partition pruning'] }),
  t('Partition pruning', 'BigQuery',
    'Skipping partitions that cannot satisfy the filter.',
    'The single biggest cost lever available. `WHERE date >= \'2024-06-01\'` prunes; `WHERE EXTRACT(MONTH FROM date) = 6` returns the same rows and scans the whole table.',
    { related: ['Partitioning'] }),
  t('Project', 'BigQuery',
    'The billing and access boundary in Google Cloud.',
    'Queries are billed to the project that runs them, not the one that owns the data — which is how you query public datasets without paying for their storage.',
    { related: ['Dataset'] }),
  t('ARRAY', 'BigQuery',
    'A repeated field: many values in one column of one row.',
    'Needs UNNEST to flatten, which is an implicit CROSS JOIN and multiplies your row count. Filter the outer table before you UNNEST.',
    { related: ['STRUCT', 'UNNEST'] }),
  t('STRUCT', 'BigQuery',
    'A nested field: one record with named sub-fields.',
    'Reach in with a dot — no UNNEST, because there is only one value. `device.category` works; `UNNEST(device)` is an error. Telling STRUCT from ARRAY on sight is the core GA4 skill.',
    { related: ['ARRAY', 'UNNEST'] }),
  t('UNNEST', 'BigQuery',
    'Flattens an array into rows.',
    'Two idioms: in FROM when you want array-grain output, and as a scalar subquery when you need several values on one row without changing the grain. The second is the one to memorise for GA4.',
    { related: ['ARRAY', 'GA4 export'] }),
  t('SAFE_DIVIDE', 'BigQuery',
    'Division that returns NULL instead of erroring on a zero denominator.',
    'The most useful BigQuery function for marketers, because every rate metric has a denominator that is sometimes zero. SAFE_CAST and the SAFE. prefix follow the same principle.',
    { related: ['Bytes scanned'] }),
  t('Slots', 'BigQuery',
    'Units of compute capacity.',
    'On-demand pricing bills bytes and gives you a shared slot pool. Flat-rate reservations buy dedicated slots and make cost predictable rather than proportional to scan size.',
    { related: ['Bytes scanned'] }),
  t('Wildcard table', 'BigQuery',
    'Querying many similarly-named tables at once with a `*` suffix.',
    'Filter on `_TABLE_SUFFIX` to restrict which tables are read — it is the partition-pruning equivalent for sharded tables like `events_20240614`.',
    { related: ['Partitioning'] }),
  t('Materialised view', 'BigQuery',
    'A view whose results are precomputed and incrementally refreshed.',
    'Unlike a plain view, it stores data and BigQuery can rewrite queries to use it automatically. The right answer when the same aggregation runs many times a day.',
    { related: ['Dataset'] }),

  // ─────────────────────────────────────────────────────── Marketing ──
  t('Activation rate', 'Marketing',
    'The share of signups that reach the product\'s aha moment.',
    'Upstream of retention, expansion and referral, and the fastest of the four to move. Defining the activation event honestly matters more than the SQL.',
    { formula: 'activated users / signups', related: ['Retention'] }),
  t('AOV', 'Marketing',
    'Average order value.',
    'Report the median beside the mean when order values are skewed, which they usually are. AOV × order count is the whole revenue model.',
    { formula: 'revenue / orders', related: ['LTV'] }),
  t('Attribution', 'Marketing',
    'Assigning credit for a conversion to marketing touches.',
    'First-touch, last-touch, linear, position-based and time-decay all redistribute the same revenue differently. Choosing one is a business decision, and none of them establish incrementality.',
    { related: ['Incrementality', 'Multi-touch attribution'] }),
  t('Blended CAC', 'Marketing',
    'All paid spend divided by all new customers, including organic ones.',
    'The honest headline and a terrible optimisation target — it charges paid media for customers organic brought in free. Always higher than any channel-level CAC, and always the number the CFO quotes.',
    { formula: 'total paid spend / all new customers', related: ['CAC'] }),
  t('CAC', 'Marketing',
    'Customer acquisition cost.',
    'The whole argument is the denominator: all customers (blended), paid-sourced only, or first-touch attributed. State which one before you state the number.',
    { formula: 'spend / new customers', related: ['Blended CAC', 'LTV:CAC'] }),
  t('Churn', 'Marketing',
    'The rate at which customers or revenue leave.',
    'Logo churn counts customers; revenue churn counts money. They tell different stories, and the denominator must be the population at the *start* of the period.',
    { formula: 'churned in period / population at period start', related: ['NRR', 'Retention'] }),
  t('Cohort', 'Marketing',
    'A group defined by when they first did something.',
    'Cohort analysis is the only way to separate "acquisition slowed" from "retention worsened", because it holds the starting point constant.',
    { related: ['Retention'] }),
  t('CPM / CPC / CPA', 'Marketing',
    'Cost per thousand impressions, per click, and per acquisition.',
    'A ladder down the funnel. CPM measures audience cost, CPC measures auction competitiveness, CPA measures the whole thing including your landing page.',
    { formula: 'spend / (impressions ÷ 1000) · spend / clicks · spend / conversions', related: ['CTR'] }),
  t('CTR', 'Marketing',
    'Click-through rate.',
    'Always weighted: total clicks over total impressions. Averaging per-row CTR gives a 12-impression day the same weight as a 40,000-impression one, and produces a number that can be seven times wrong.',
    { formula: 'clicks / impressions', related: ['CPM / CPC / CPA'] }),
  t('Funnel', 'Marketing',
    'A sequence of steps with drop-off measured between them.',
    'Report step-to-step rates, not step-to-top: a funnel measured against the top makes every step after the leaky one look broken too. Also decide whether it is strict-order or any-order, and say which.',
    { related: ['Conversion rate'] }),
  t('Conversion rate', 'Marketing',
    'The share of some population that converted.',
    'Per session, per user, per new user, per engaged session — four legitimate answers differing by more than 2×. Nobody who asks for "the conversion rate" knows which they mean; ask what decision it feeds.',
    { formula: 'conversions / sessions (or users, or …)', related: ['Funnel'] }),
  t('GA4 export', 'Marketing',
    'Google Analytics 4\'s raw event stream in BigQuery.',
    'One row per event. event_date is a YYYYMMDD string, event_timestamp is microseconds, and everything interesting is inside repeated event_params. It is where most marketers meet real SQL.',
    { related: ['UNNEST', 'user_pseudo_id'] }),
  t('Incrementality', 'Marketing',
    'Revenue that would not have happened without the spend.',
    'Every attribution model in existence is correlational. Brand search shows spectacular ROAS because it captures demand other channels created. Only a holdout test separates incremental from captured.',
    { related: ['Attribution', 'ROAS'] }),
  t('LTV', 'Marketing',
    'Lifetime value — total profit or revenue from a customer.',
    'Historical LTV understates young cohorts, because they have had less time to spend. Fixed-window cohort LTV (90-day, 12-month) is the only fair comparison across acquisition months.',
    { formula: 'cumulative revenue per customer', related: ['LTV:CAC', 'Payback period'] }),
  t('LTV:CAC', 'Marketing',
    'The ratio deciding whether acquisition is worth doing.',
    '3:1 is the conventional floor. Below 1:1 you are buying revenue at a loss. The ratio is only as honest as the LTV window behind it.',
    { formula: 'LTV / CAC', related: ['LTV', 'CAC'] }),
  t('MQL / SQL', 'Marketing',
    'Marketing-qualified and sales-qualified lead.',
    'Stage labels in a B2B funnel. Count them by stage *dates*, not by the current lifecycle label — the label only says where someone is now, so counting it undercounts every stage already passed.',
    { related: ['Funnel'] }),
  t('MRR', 'Marketing',
    'Monthly recurring revenue.',
    'Flat MRR can mean nothing happened or that new business and churn cancelled out. The bridge — new, expansion, contraction, churned, reactivation — is what shows which.',
    { related: ['NRR', 'Churn'] }),
  t('Multi-touch attribution', 'Marketing',
    'Splitting conversion credit across several touches.',
    'Worth building only if journeys are actually multi-touch. In most datasets single-touch paths dominate, which makes elaborate models expensive theatre.',
    { related: ['Attribution'] }),
  t('NRR', 'Marketing',
    'Net revenue retention.',
    'What a fixed cohort of revenue is worth later, including expansion and contraction. Above 100% means existing customers grow faster than they leave — the number SaaS investors ask for first.',
    { formula: '(starting MRR + expansion − contraction − churn) / starting MRR', related: ['MRR', 'Churn'] }),
  t('Payback period', 'Marketing',
    'How long it takes to earn back the cost of acquiring a customer.',
    'Decides whether growth self-funds. A three-month payback finances itself; an eighteen-month payback means every new customer is a loan.',
    { formula: 'CAC / monthly revenue per customer', related: ['CAC', 'LTV:CAC'] }),
  t('Retention', 'Marketing',
    'The share of a cohort still active after n periods.',
    'Anchored to the cohort\'s starting size, not the previous period. The shape of the curve matters more than any single point: a curve that flattens has a business, one that keeps falling does not.',
    { formula: 'active in period n / cohort size', related: ['Cohort', 'Churn'] }),
  t('RFM', 'Marketing',
    'Recency, frequency, monetary segmentation.',
    'Score each dimension into quartiles and name the cells. "At risk" — high frequency, low recency — is the most valuable segment there is: they proved they like you and then stopped.',
    { related: ['Segmentation'] }),
  t('ROAS', 'Marketing',
    'Return on ad spend, as a multiple.',
    'Platform-reported ROAS overclaims structurally, because Meta and Google each count the same conversion on their own attribution window. The warehouse number is lower and is the one to plan with.',
    { formula: 'revenue / spend', related: ['Attribution', 'Incrementality'] }),
  t('Segmentation', 'Marketing',
    'Dividing customers into groups that behave differently.',
    'A segment without a size and a revenue number attached cannot be prioritised, and a segment nobody can build a campaign against is a slide, not a segment.',
    { related: ['RFM'] }),
  t('user_pseudo_id', 'Marketing',
    'GA4\'s device-scoped identifier.',
    '"Users" in GA4 means devices. One person on a phone and a laptop is two users; two people sharing a laptop are one. Every cross-device number is an estimate built on top of that.',
    { related: ['GA4 export'] }),
  t('View-through conversion', 'Marketing',
    'A conversion credited to an ad that was seen but not clicked.',
    'How display and video prospecting is measured, and why those campaigns show zero last-click orders. Whether you believe them is the same question as incrementality.',
    { related: ['Attribution', 'Incrementality'] }),
];

export function glossaryByCategory(category: GlossaryTerm['category']): GlossaryTerm[] {
  return GLOSSARY.filter((g) => g.category === category)
    .sort((a, b) => a.term.localeCompare(b.term));
}

export function findTerm(term: string): GlossaryTerm | undefined {
  return GLOSSARY.find((g) => g.term.toLowerCase() === term.toLowerCase());
}
